### PR TITLE
Update: Compatibility with 2023.5.0

### PR DESCRIPTION
**Pull request by JurajNyiri**

### CODE REVIEW

**Comment by tjorim** [comment]
Can not install on beta anymore:
You are running Home Assistant version '2023.5.0b8', but this repository requires minimum version '2023.5.0' to be installed.

**Comment by JurajNyiri** [comment]
Hi, install manually for now, HA should release stable pretty soon, it's Wednesday.

**Comment by thundergreen** [comment]
When I install manually it won't work . Integration not shown

Juraj Nyíri ***@***.***> schrieb am Mi., 3. Mai 2023, 13:58:

**Comment by thundergreen** [comment]
Did it this way. Nevermind..will wait rollout of release and install via
hacs ;)


Juraj Nyíri ***@***.***> schrieb am Mi., 3. Mai 2023, 18:12:

**Pull request merged**
