### PR TITLE
feat(setup): improve setup config flow

### PR DESCRIPTION
**Pull request by CFenner**
Use "next" button to indicate multi step setup. 

Bildschirmfoto 2022-10-18 um 10 47 23

### CODE REVIEW

**Review by JurajNyiri — CHANGES_REQUESTED** [review]
Nice find.

We can use the next button but we should not have x/4 since those are device specific and it can skip steps if they are not needed.

**Comment by CFenner** [comment]
I reverted the changes to the title.

**Review by JurajNyiri — APPROVED** [review]

**Comment by JurajNyiri** [comment]
Thank you!

**Comment by JurajNyiri** [comment]
Released in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/4.0.0 .

**Comment by JurajNyiri** [comment]
I am going to revert this. It is not working for me with 
```

TypeError: FlowHandler.async_show_form() got an unexpected keyword argument 'LastStep'
```

**Comment by CFenner** [comment]
Sorry @JurajNyiri somehow I mixed up the parameter name, should've copy&paste it..

**Pull request merged**
